graph LR
    Topico[Visão Computacional] --> Item1[Definição]
    Topico --> Item2[Dia a Dia]
    Topico --> Item3[Introdução]

    Item1 --> I1_Sub1[Subitem 1]
    I1_Sub1 --> I1_Sub2[Subitem 2]

    Item2 --> I2_Sub1[Subitem 1]
    I2_Sub1 --> I2_Sub2[Subitem 2]

    Item3 --> I3_Sub1[Subitem 1]
    I3_Sub1 --> I3_Sub2[Subitem 2]